###
// get All
GET http://localhost:3000/lectures/ HTTP/1.1

###
//Get BY Course
GET http://localhost:3000/lectures/MWA HTTP/1.1


###
POST http://localhost:3000/lectures HTTP/1.1
content-type: application/json

{
"course":"BDA",
"lecture":"5"
}

###
PUT http://localhost:3000/lectures/BDA HTTP/1.1
content-type: application/json

{
"course":"BDA ADVANCED",
"lecture":"1000"
}

###
DELETE http://localhost:3000/lectures/Ari HTTP/1.1

###
// SEARCH 
POST http://localhost:3000/search/BD HTTP/1.1


