###
GET  http://localhost:3000/locations HTTP/1.1
content-type: application/json


###
POST http://localhost:3000/locations HTTP/1.1
content-type: application/json

[
  {    
    "name": "WaleMart",
    "category": "Market",
    "location": [-91.993186,41.008382]
  },
  {
    "name": "MUM",
    "category": "University",
    "location": [-91.967291,41.018059]
  },
  {
    "name": "Des Monnes",
    "category": "City",
    "location": [-93.6765561,41.5667771]
  }
]

###
POST http://localhost:3000/find HTTP/1.1
content-type: application/json

{
    "name": "MUM",
    "category": "University",
    "location": [-91.967291,41.018059]
  }